#!/bin/sh
set -e
#cp -r /lib/DockLight/data /tmp/DockLightData
#rm -f /lib/DockLight/docklight
#rm -f /lib/DockLight/docklight.ico
#rm -f /lib/DockLight/docklight.ini

if [ "$1" = "purge" ]; then
  rm -fr /lib/DockLight	
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
   
    # Remove my changes to the db.
    db_purge
fi


exit 0



