Document: docklight
Title: Debian docklight Manual
Author: <insert document author here>
Abstract: This manual describes what docklight is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/docklight/docklight.sgml.gz

Format: postscript
Files: /usr/share/doc/docklight/docklight.ps.gz

Format: text
Files: /usr/share/doc/docklight/docklight.text.gz

Format: HTML
Index: /usr/share/doc/docklight/html/index.html
Files: /usr/share/doc/docklight/html/*.html
